name: Publish Python Package

on: push

jobs:
  build:
    name: Build artifacts for PyPi on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.9
            3.10
            3.11
            3.12

      - name: Install Poetry
        run: make install poetry

      # Publish the source distribution with the version that's in
      # the repository, otherwise the tests will fail
      - name: Compile source distribution
        run: python3 -m poetry build --format=sdist
        if: startsWith(matrix.os, 'ubuntu')

      - name: Build wheels
        run: poetry build --format wheel

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs:
    - build
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: dist/
          skip_existing: true
          repository_url: https://test.pypi.org/legacy/
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}